from PyQt5 import QtCore, QtGui, QtWidgets


class AddTestUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1040, 915)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 911))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.addQuestionButton = QtWidgets.QPushButton(self.tab)
        self.addQuestionButton.setGeometry(QtCore.QRect(370, 20, 281, 28))
        self.addQuestionButton.setObjectName("addQuestionButton")
        self.testEdit = QtWidgets.QLineEdit(self.tab)
        self.testEdit.setGeometry(QtCore.QRect(280, 70, 471, 22))
        self.testEdit.setObjectName("testEdit")
        self.testAddTable = QtWidgets.QTableWidget(self.tab)
        self.testAddTable.setGeometry(QtCore.QRect(0, 110, 1041, 781))
        self.testAddTable.setObjectName("testAddTable")
        self.testAddTable.setColumnCount(4)
        self.testAddTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.testAddTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.testAddTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.testAddTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.testAddTable.setHorizontalHeaderItem(3, item)
        self.testAddTable.horizontalHeader().setCascadingSectionResizes(False)
        self.testAddTable.horizontalHeader().setDefaultSectionSize(344)
        self.testAddTable.horizontalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addQuestionButton.setText(_translate("Form", "Добавить вопрос"))
        self.testEdit.setPlaceholderText(_translate("Form", "Название теста"))
        item = self.testAddTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Тип теста (выбор/ответ)"))
        item = self.testAddTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Вопрос"))
        item = self.testAddTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Варианты ответа (если нужны)."))
        item = self.testAddTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Правильный ответ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "AddTest"))
