from PyQt5 import QtCore, QtGui, QtWidgets


class ReadTaskUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1246, 896)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1251, 901))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.save = QtWidgets.QPushButton(self.tab)
        self.save.setGeometry(QtCore.QRect(0, 0, 111, 51))
        self.save.setObjectName("save")
        self.taskText = QtWidgets.QTextEdit(self.tab)
        self.taskText.setGeometry(QtCore.QRect(0, 50, 1241, 711))
        self.taskText.setReadOnly(True)
        self.taskText.setObjectName("taskText")
        self.lastTheme = QtWidgets.QPushButton(self.tab)
        self.lastTheme.setGeometry(QtCore.QRect(110, 0, 111, 51))
        self.lastTheme.setObjectName("lastTheme")
        self.nextTheme = QtWidgets.QPushButton(self.tab)
        self.nextTheme.setGeometry(QtCore.QRect(220, 0, 111, 51))
        self.nextTheme.setObjectName("nextTheme")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1241, 641))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget.setRowCount(12)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(600)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.save.setText(_translate("Form", "Save"))
        self.lastTheme.setText(_translate("Form", "<"))
        self.nextTheme.setText(_translate("Form", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Задание"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "К1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "K2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "K3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "K4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "K5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "K6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "K7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "K8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "K9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "K10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "K11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "K12"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "За что ставятся баллы"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Максимальный балл"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "Определение проблемы (допустимы разные формулировки, главное, чтобы был верно передан смысл). Если по К1 стоит 0, то по К2, К3 и К4 тоже выставляется ноль."))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "Комментарий к проблеме"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "5 (по баллу за каждый  пример, пояснение к нему и связь между примерами)"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "Позиция автора"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "Своя позиция"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "1 (ставится, если позиция понятно выражена и аргументирована)"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "Логическое построение текста, смысловая связность предложений"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "Точность и выразительность речи"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "2 (максимальный балл ставят только при наличии максимума в критерии К10)"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "Соблюдение орфографических норм "))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "Соблюдение пунктуационных норм"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "Соблюдение грамматических норм"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "Соблюдение речевых норм"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "Соблюдение этических норм"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "Соблюдение фактической точности"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Form", "1"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Критерии оценки"))
