from PyQt5 import QtCore, QtGui, QtWidgets


class UserUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1465, 918)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 270, 701, 591))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.wikiLine = QtWidgets.QLineEdit(self.tab)
        self.wikiLine.setGeometry(QtCore.QRect(0, 10, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wikiLine.setFont(font)
        self.wikiLine.setText("")
        self.wikiLine.setObjectName("wikiLine")
        self.wikiText = QtWidgets.QTextEdit(self.tab)
        self.wikiText.setGeometry(QtCore.QRect(0, 110, 461, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wikiText.setFont(font)
        self.wikiText.setReadOnly(True)
        self.wikiText.setObjectName("wikiText")
        self.wikiGet = QtWidgets.QPushButton(self.tab)
        self.wikiGet.setGeometry(QtCore.QRect(0, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wikiGet.setFont(font)
        self.wikiGet.setObjectName("wikiGet")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.authorEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.authorEdit.setText("")
        self.authorEdit.setObjectName("authorEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.authorEdit)
        self.find_btn = QtWidgets.QPushButton(self.tab_2)
        self.find_btn.setGeometry(QtCore.QRect(500, 10, 191, 28))
        self.find_btn.setObjectName("find_btn")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 60, 501, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.toWriteNotes = QtWidgets.QPushButton(self.tab_3)
        self.toWriteNotes.setGeometry(QtCore.QRect(160, 130, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toWriteNotes.setFont(font)
        self.toWriteNotes.setObjectName("toWriteNotes")
        self.toWriteEssay = QtWidgets.QPushButton(self.tab_3)
        self.toWriteEssay.setGeometry(QtCore.QRect(160, 300, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toWriteEssay.setFont(font)
        self.toWriteEssay.setObjectName("toWriteEssay")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(730, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(730, 30, 711, 841))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.testName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.testName.setText("")
        self.testName.setObjectName("testName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.testName)
        self.findTest_btn = QtWidgets.QPushButton(self.tab_4)
        self.findTest_btn.setGeometry(QtCore.QRect(500, 0, 201, 28))
        self.findTest_btn.setObjectName("findTest_btn")
        self.scrollTests = QtWidgets.QScrollArea(self.tab_4)
        self.scrollTests.setGeometry(QtCore.QRect(0, 30, 701, 781))
        self.scrollTests.setWidgetResizable(True)
        self.scrollTests.setObjectName("scrollTests")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 699, 779))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollTests.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.testsTable = QtWidgets.QTableWidget(self.tab_5)
        self.testsTable.setGeometry(QtCore.QRect(0, 30, 701, 781))
        self.testsTable.setRowCount(0)
        self.testsTable.setColumnCount(3)
        self.testsTable.setObjectName("testsTable")
        self.testsTable.horizontalHeader().setVisible(False)
        self.testsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.testsTable.horizontalHeader().setDefaultSectionSize(233)
        self.testsTable.horizontalHeader().setHighlightSections(True)
        self.testsTable.verticalHeader().setVisible(False)
        self.testsTable.verticalHeader().setCascadingSectionResizes(True)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.madeTestName = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.madeTestName.setText("")
        self.madeTestName.setObjectName("madeTestName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.madeTestName)
        self.findMadeTest_btn = QtWidgets.QPushButton(self.tab_5)
        self.findMadeTest_btn.setGeometry(QtCore.QRect(500, 0, 201, 28))
        self.findMadeTest_btn.setObjectName("findMadeTest_btn")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 261))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1465, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wikiLine.setPlaceholderText(_translate("MainWindow", "Введите слово"))
        self.wikiText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.wikiText.setPlaceholderText(_translate("MainWindow", "Определение слова"))
        self.wikiGet.setText(_translate("MainWindow", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "WIKI"))
        self.nameEdit.setPlaceholderText(_translate("MainWindow", "Название"))
        self.authorEdit.setPlaceholderText(_translate("MainWindow", "Автор"))
        self.find_btn.setText(_translate("MainWindow", "Найти"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "BOOKS"))
        self.toWriteNotes.setText(_translate("MainWindow", "Писать заметки"))
        self.toWriteEssay.setText(_translate("MainWindow", "Писать сочинение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Edit"))
        self.label_5.setText(_translate("MainWindow", "ТЕСТЫ:"))
        self.label_6.setText(_translate("MainWindow", "Название:"))
        self.findTest_btn.setText(_translate("MainWindow", "Найти"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Все тесты"))
        self.label_7.setText(_translate("MainWindow", "Название:"))
        self.findMadeTest_btn.setText(_translate("MainWindow", "Найти"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Пройденные тесты"))
        self.label.setText(_translate("MainWindow", "BookFoU"))
